package com.repcheck.bills.metadata.app

import java.time.Instant
import java.util.UUID

import cats.effect.{Async, ExitCode, Resource, Sync}
import cats.syntax.all._

import org.http4s.ember.client.EmberClientBuilder

import fs2.Stream
import fs2.io.net.Network

import doobie.postgres.implicits._
import doobie.util.Write
import doobie.util.transactor.Transactor

import pureconfig.ConfigSource

import repcheck.ingestion.common.api.CongressGovClientConfig
import repcheck.ingestion.common.db.{DatabaseConfig, TransactorResource}
import repcheck.ingestion.common.logging.{LogContext, PipelineLogger, PipelineLoggerFactory}
import repcheck.ingestion.common.placeholders.{DefaultPlaceholderCreator, DoobieEntityRepository}
import repcheck.pipeline.models.errors.RetryWrapper
import repcheck.pipeline.models.metadata.{PipelineRunSummary, ProcessingResult}
import repcheck.shared.models.congress.dos.member.MemberDO

import com.repcheck.bills.common.persistence.{
  DoobieBillCosponsorRepository,
  DoobieBillHistoryArchiver,
  DoobieBillRepository,
  DoobieBillSubjectRepository,
  DoobieMemberLookupRepository,
}
import com.repcheck.bills.metadata.api.BillsApiClient
import com.repcheck.bills.metadata.config.BillMetadataConfig
import com.repcheck.bills.metadata.pipeline.BillMetadataProcessor

private[app] object BillMetadataPipeline {

  private val PipelineName = "bill-metadata-pipeline"

  final case class AppConfig(
    database: DatabaseConfig,
    congressApi: CongressGovClientConfig,
    pipeline: BillMetadataConfig,
  ) derives pureconfig.ConfigReader

  /**
   * Custom [[Write]] for [[MemberDO]] that omits `memberId` -- the `id` column is auto-generated by the BIGSERIAL
   * sequence. This produces 14 positional parameters matching the 14 non-PK columns in the INSERT.
   */
  implicit private val memberInsertWrite: Write[MemberDO] = {
    type Row = (
      String,
      Option[String],
      Option[String],
      Option[String],
      Option[String],
      Option[String],
      Option[String],
      Option[String],
      Option[String],
      Option[Int],
      Option[String],
      Option[String],
      Option[String],
      Option[Instant],
    )
    Write[Row].contramap[MemberDO] { m =>
      (
        m.naturalKey,
        m.firstName,
        m.lastName,
        m.directOrderName,
        m.invertedOrderName,
        m.honorificName,
        m.birthYear,
        m.currentParty,
        m.state,
        m.district,
        m.imageUrl,
        m.imageAttribution,
        m.officialUrl,
        m.updateDate.map(Instant.parse),
      )
    }
  }

  private val MemberInsertSql: String =
    """INSERT INTO members (
      |  natural_key, first_name, last_name, direct_order_name, inverted_order_name,
      |  honorific_name, birth_year, current_party, state, district, image_url, image_attribution,
      |  official_url, update_date
      |) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      |ON CONFLICT (natural_key) DO NOTHING""".stripMargin

  def run[F[_]: Async: Network](args: List[String]): F[ExitCode] = {
    val _ = args // args reserved for future CLI config override support
    for {
      config <- Sync[F].delay {
        ConfigSource.default.loadOrThrow[AppConfig]
      }
      logger <- PipelineLoggerFactory.make[F](PipelineName)
      exitCode <- buildResources[F](config).use {
        case (xa, httpClient) =>
          val billRepo         = new DoobieBillRepository
          val cosponsorRepo    = new DoobieBillCosponsorRepository
          val subjectRepo      = new DoobieBillSubjectRepository
          val historyArchiver  = new DoobieBillHistoryArchiver
          val memberLookup     = new DoobieMemberLookupRepository
          val placeholder      = new DefaultPlaceholderCreator[F]
          val memberEntityRepo = new DoobieEntityRepository[F, MemberDO](xa, MemberInsertSql)
          val retryWrapper     = new RetryWrapper[F]((_, _, _, _, _, _) => Async[F].unit)
          val apiClient        = BillsApiClient[F](config.congressApi, httpClient, retryWrapper)

          val processor = new BillMetadataProcessor[F](
            apiClient = apiClient,
            billRepo = billRepo,
            cosponsorRepo = cosponsorRepo,
            subjectRepo = subjectRepo,
            historyArchiver = historyArchiver,
            memberLookupRepo = memberLookup,
            placeholderCreator = placeholder,
            memberEntityRepo = memberEntityRepo,
            xa = xa,
            config = config.pipeline,
            logger = logger,
          )

          val correlationId = UUID.randomUUID()
          val resultStream  = processor.streamAll(correlationId)
          execute[F](resultStream, logger, PipelineName, correlationId)
      }
    } yield exitCode
  }

  private def buildResources[F[_]: Async: Network](
    config: AppConfig
  ): Resource[F, (Transactor[F], org.http4s.client.Client[F])] =
    for {
      xa         <- TransactorResource.make[F](config.database)
      httpClient <- EmberClientBuilder.default[F].build
    } yield (xa, httpClient)

  /**
   * Testable pipeline execution logic. Accepts a pre-built result stream and logger so that tests can inject stubs
   * without needing to construct the full dependency graph.
   */
  private[app] def execute[F[_]: Async](
    resultStream: Stream[F, ProcessingResult],
    logger: PipelineLogger[F],
    pipelineName: String,
    correlationId: UUID,
  ): F[ExitCode] = {
    val logCtx = LogContext(runId = correlationId.toString, stepName = pipelineName)

    for {
      startedAt   <- Async[F].realTimeInstant
      results     <- resultStream.compile.toList
      completedAt <- Async[F].realTimeInstant
      summary = PipelineRunSummary.fromResults(
        runId = correlationId,
        pipelineName = pipelineName,
        startedAt = startedAt,
        completedAt = completedAt,
        results = results,
      )
      _ <- logger.info(
        logCtx,
        s"Pipeline completed: ${summary.itemsProcessed} processed, ${summary.itemsSucceeded} succeeded, ${summary.itemsFailed} failed",
      )
      exitCode =
        if (summary.itemsFailed == 0) { ExitCode.Success }
        else { ExitCode.Error }
    } yield exitCode
  }

}
