package repcheck.ingestion.votes.lis

import java.time.Instant

import cats.effect.Async
import cats.syntax.all._

import doobie.ConnectionIO
import doobie.implicits._
import doobie.util.transactor.Transactor

import repcheck.ingestion.common.logging.{LogContext, PipelineLogger}
import repcheck.members.common.persistence.LisMemberRepository
import repcheck.shared.models.congress.dos.member.LisMemberDO
import repcheck.shared.models.congress.dto.vote.SenateVoteXmlDTO

/**
 * Upserts a `lis_members` row for every senator observed on a senate.gov roll-call XML DTO, returning the surrogate
 * `lis_members.id` indexed by the natural key (the senate.gov LIS identifier, a string like `"S428"`).
 *
 * ==Scope (post-refactor per PR #43 review direction)==
 *
 * Votes-pipeline's ONLY LIS-side responsibility is to keep the `lis_members` table current with the identity snapshot
 * senate.gov returned on each roll call. It does NOT:
 *   - create placeholder rows in the `members` table;
 *   - insert rows into `member_lis_mapping`;
 *   - resolve any bioguide id;
 *   - touch any table other than `lis_members`.
 *
 * The `lis-mapping-refresher` job owns the forward mapping (LIS id → bioguide → `members` upsert →
 * `member_lis_mapping`). Downstream, the vote-positions upsert path uses `VotePositionDO.lisMemberId` to identify
 * Senate roll-call positions (dual-identity per migration 023).
 *
 * ==Natural key vs. surrogate id==
 *
 * Senate.gov XML's LIS identifier is a short string (letter + digits — e.g. `"S428"`). That string is the
 * `lis_members.natural_key` (TEXT). The surrogate `lis_members.id` (BIGSERIAL) is generated by PostgreSQL and is what
 * this component returns. The two must not be confused: the natural key is the human-facing identifier, the surrogate
 * id is the FK target for `vote_positions.lis_member_id` and `member_lis_mapping.lis_member_id`.
 */
trait LisResolver[F[_]] {

  /**
   * Upsert one `lis_members` row per senator in `senateVote.members`, keyed by natural key, and return `Map[naturalKey,
   * lis_members.id]` for every distinct senator seen. An empty senators list resolves to the empty map with no SQL
   * interaction. All upserts commit inside a single transaction.
   */
  def resolve(senateVote: SenateVoteXmlDTO): F[Map[String, Long]]
}

object LisResolver {

  /**
   * Factory for the default implementation. Construction arguments are exactly the live dependencies used by
   * [[DefaultLisResolver]] — tests can also stub the trait directly via Mockito to avoid pulling in Doobie machinery.
   */
  def apply[F[_]: Async](
    lisMemberRepo: LisMemberRepository,
    xa: Transactor[F],
    logger: PipelineLogger[F],
  ): LisResolver[F] =
    new DefaultLisResolver[F](lisMemberRepo, xa, logger)

}

/**
 * Default implementation of [[LisResolver]]. Separated from the trait so downstream processors (P3.1) can compose the
 * inner [[resolveConnection]] `ConnectionIO` inside a larger transaction if they need the upserts and a vote-positions
 * write to commit atomically.
 */
final class DefaultLisResolver[F[_]: Async](
  lisMemberRepo: LisMemberRepository,
  xa: Transactor[F],
  logger: PipelineLogger[F],
) extends LisResolver[F] {

  private val StepName: String = "votes-lis-resolver"

  override def resolve(senateVote: SenateVoteXmlDTO): F[Map[String, Long]] = {
    val logCtx = LogContext(
      runId = buildRunLabel(senateVote),
      stepName = StepName,
    )

    val distinctSenators = dedupSenators(senateVote)

    for {
      now    <- Async[F].delay(Instant.now())
      result <- resolveConnection(distinctSenators, now).transact(xa)
      _      <- logUpserts(logCtx, senateVote, result)
    } yield result
  }

  /**
   * Build the `ConnectionIO` that upserts one `lis_members` row per distinct senator and returns `Map[naturalKey,
   * lis_members.id]`. Exposed as `private[lis]` so downstream processor code and integration tests can embed it inside
   * a larger transaction. The public `resolve` simply wraps this and `transact`s.
   */
  private[lis] def resolveConnection(
    senators: List[SenatorRow],
    now: Instant,
  ): ConnectionIO[Map[String, Long]] =
    senators
      .traverse { s =>
        val dto = buildLisMemberDO(s, now)
        lisMemberRepo.upsertByNaturalKey(dto).map(id => s.naturalKey -> id)
      }
      .map(_.toMap)

  /**
   * Collect the distinct senators from the DTO, keyed by natural key. Multiple entries with the same natural key are
   * deduped last-wins — this happens in practice when a vote DTO accidentally carries a duplicate senator row, and the
   * downstream vote-positions upsert path already tolerates the same position being reported twice.
   */
  private[lis] def dedupSenators(senateVote: SenateVoteXmlDTO): List[SenatorRow] =
    senateVote.members
      .map { m =>
        SenatorRow(
          naturalKey = m.lisMemberId,
          firstName = m.firstName,
          lastName = m.lastName,
          party = m.party,
          state = m.state,
        )
      }
      .foldLeft(collection.immutable.ListMap.empty[String, SenatorRow]) { (acc, row) =>
        acc.updated(row.naturalKey, row)
      }
      .values
      .toList

  /**
   * Convert a collapsed [[SenatorRow]] into a [[LisMemberDO]] with `lastVerified = now`. `id = 0L` because the upsert
   * ignores it and the database returns the assigned BIGSERIAL from the `RETURNING` clause. Empty strings on DTO fields
   * become `None` so an intermittent senate.gov blank does not overwrite a previously populated value with an empty
   * string — the `ON CONFLICT DO UPDATE` clause only overwrites with `EXCLUDED` values, but `None` round-trips as
   * `NULL` which is the expected representation of a blank.
   */
  private[lis] def buildLisMemberDO(row: SenatorRow, now: Instant): LisMemberDO =
    LisMemberDO(
      id = 0L,
      naturalKey = row.naturalKey,
      firstName = Some(row.firstName).filter(_.nonEmpty),
      lastName = Some(row.lastName).filter(_.nonEmpty),
      party = Some(row.party).filter(_.nonEmpty),
      state = Some(row.state).filter(_.nonEmpty),
      lastVerified = Some(now),
      createdAt = None,
    )

  /**
   * Emit a single info log summarizing the upsert activity for this resolve call. A silent log is fine when the vote
   * had no senators (empty DTO) — a no-op elsewhere in the pipeline would already raise if a senate vote had no
   * senators at all.
   */
  private[lis] def logUpserts(
    logCtx: LogContext,
    senateVote: SenateVoteXmlDTO,
    result: Map[String, Long],
  ): F[Unit] =
    if (result.isEmpty) {
      Async[F].unit
    } else {
      logger.info(
        logCtx,
        s"Upserted ${result.size.toString} lis_members rows for senate vote ${buildRunLabel(senateVote)}",
      )
    }

  /**
   * Compose a short human-readable label for the senate vote being resolved — used as the `runId` on log context and in
   * the upsert-count log message. Format: `{congress}-{session}-{voteNumber}`.
   */
  private[lis] def buildRunLabel(senateVote: SenateVoteXmlDTO): String =
    s"${senateVote.congress.toString}-${senateVote.session.toString}-${senateVote.voteNumber.toString}"

}

/**
 * Internal representation of one senator row after `senateVote.members` has been deduped by natural key. Exposed at
 * `private[lis]` solely for test access.
 */
final private[lis] case class SenatorRow(
  naturalKey: String,
  firstName: String,
  lastName: String,
  party: String,
  state: String,
)
