package repcheck.members.common.persistence

import doobie._
import doobie.implicits._

import repcheck.pipeline.models.constants.Tables
import repcheck.shared.models.congress.dos.member.MemberPartyHistoryDO

/**
 * Doobie implementation of [[MemberPartyHistoryRepository]]. `appendNew` uses an `INSERT ... ON CONFLICT (member_id,
 * start_year, party_name) DO UPDATE SET party_abbreviation = EXCLUDED.party_abbreviation` because the
 * `member_party_history` schema carries a unique constraint `uq_member_party_history UNIQUE (member_id, start_year,
 * party_name)` (see migration `020-widen-member-party-history-unique.sql`).
 *
 * The 3-column target preserves mid-year party switches — a member of Congress can legally switch parties any number of
 * times per year, and Congress.gov's `/member/{bioguideId}` API models this with a `partyHistory[]` array where two
 * entries in the same `startYear` with different `partyName` values are valid. A 2-column `(member_id, start_year)`
 * target would collapse such a switch into a single row.
 *
 * On conflict we `UPDATE` `party_abbreviation` (the only non-key column) rather than `DO NOTHING`. Semantically this
 * says "always reflect the latest ingested abbreviation". In practice `party_abbreviation` is enum-constrained by
 * `party_abbreviation_type` (values `{D, R, I}`) and is uniquely determined by `party_name`, so the UPDATE is
 * functionally a no-op for any valid input — but using `DO UPDATE SET` keeps the contract explicit and is a safe
 * default if the enum is ever widened (e.g. to add `L` for Libertarian).
 *
 * The table's `id` column is `BIGSERIAL PRIMARY KEY` (added in migration 011), so it is omitted from the INSERT list
 * and generated by the database.
 */
class DoobieMemberPartyHistoryRepository extends MemberPartyHistoryRepository {

  private val table = Fragment.const(Tables.MemberPartyHistory)

  private type InsertRow = (
    Long,           // member_id
    Option[String], // party_name
    Option[String], // party_abbreviation
    Option[Int],    // start_year
  )

  override def appendNew(memberId: Long, entries: List[MemberPartyHistoryDO]): ConnectionIO[Unit] = {
    // party_name and party_abbreviation are both party_abbreviation_type ({D, R, I}) PostgreSQL enum columns.
    // party_name was widened from party_type to party_abbreviation_type in migration 021.
    // The DO carries them as Option[String], so we cast at the bind sites to avoid
    // `column X is of type Y but expression is of type character varying` errors.
    val insert = Update[InsertRow](
      s"INSERT INTO ${Tables.MemberPartyHistory} (member_id, party_name, party_abbreviation, start_year) " +
        "VALUES (?, ?::party_abbreviation_type, ?::party_abbreviation_type, ?) " +
        "ON CONFLICT (member_id, start_year, party_name) " +
        "DO UPDATE SET party_abbreviation = EXCLUDED.party_abbreviation"
    )

    val rows: List[InsertRow] = entries.map(e => (memberId, e.partyName, e.partyAbbreviation, e.startYear))

    insert.updateMany(rows).map(_ => ())
  }

  override def findByMemberId(memberId: Long): ConnectionIO[List[MemberPartyHistoryDO]] =
    sql"""SELECT id, member_id, party_name, party_abbreviation, start_year
          FROM $table
          WHERE member_id = $memberId"""
      .query[MemberPartyHistoryDO]
      .to[List]

}
