package repcheck.members.common.persistence

import doobie._
import doobie.implicits._

import repcheck.pipeline.models.constants.Tables
import repcheck.shared.models.congress.dos.member.MemberPartyHistoryDO

/**
 * Doobie implementation of [[MemberPartyHistoryRepository]]. `appendNew` uses an `INSERT ... ON CONFLICT (member_id,
 * start_year) DO NOTHING` because the `member_party_history` schema carries a unique constraint
 * `uq_member_party_history UNIQUE (member_id, start_year)` (see migration `001-initial-schema.sql`). Upstream
 * change-detection should prevent most duplicate calls, but the `ON CONFLICT` clause keeps the operation safe if the
 * same entries are appended twice.
 *
 * The table's `id` column is `BIGSERIAL PRIMARY KEY` (added in migration 011), so it is omitted from the INSERT list
 * and generated by the database.
 */
class DoobieMemberPartyHistoryRepository extends MemberPartyHistoryRepository {

  private val table = Fragment.const(Tables.MemberPartyHistory)

  private type InsertRow = (
    Long,           // member_id
    Option[String], // party_name
    Option[String], // party_abbreviation
    Option[Int],    // start_year
  )

  override def appendNew(memberId: Long, entries: List[MemberPartyHistoryDO]): ConnectionIO[Unit] = {
    // party_name and party_abbreviation are PostgreSQL enum types (party_type, party_abbreviation_type)
    // created by migration 013. The DO carries them as Option[String], so we cast at the bind sites to
    // avoid `column X is of type Y but expression is of type character varying` errors.
    val insert = Update[InsertRow](
      s"INSERT INTO ${Tables.MemberPartyHistory} (member_id, party_name, party_abbreviation, start_year) " +
        "VALUES (?, ?::party_type, ?::party_abbreviation_type, ?) " +
        "ON CONFLICT (member_id, start_year) DO NOTHING"
    )

    val rows: List[InsertRow] = entries.map(e => (memberId, e.partyName, e.partyAbbreviation, e.startYear))

    insert.updateMany(rows).map(_ => ())
  }

  override def findByMemberId(memberId: Long): ConnectionIO[List[MemberPartyHistoryDO]] =
    sql"""SELECT id, member_id, party_name, party_abbreviation, start_year
          FROM $table
          WHERE member_id = $memberId"""
      .query[MemberPartyHistoryDO]
      .to[List]

}
